# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rehab.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brehab.proto\x12\x05rehab\"H\n\x05Joint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x12\x12\n\nvisibility\x18\x05 \x01(\x02\"\x94\x01\n\x05\x46rame\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x10\n\x08\x66rame_no\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\x01\x12\x1c\n\x06joints\x18\x05 \x03(\x0b\x32\x0c.rehab.Joint\x12\x10\n\x08\x66\x65\x61tures\x18\x06 \x03(\x02\x12\x11\n\tlabels_th\x18\x07 \x03(\t\"\x7f\n\x07Session\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_info\x18\x03 \x01(\t\x12\x10\n\x08start_ts\x18\x04 \x01(\x01\x12\x0e\n\x06\x65nd_ts\x18\x05 \x01(\x01\x12\x18\n\x10\x63\x61libration_data\x18\x06 \x01(\x0c\"Q\n\x07\x43\x61ption\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x01\x12\x0c\n\x04text\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rehab_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_JOINT']._serialized_start=22
  _globals['_JOINT']._serialized_end=94
  _globals['_FRAME']._serialized_start=97
  _globals['_FRAME']._serialized_end=245
  _globals['_SESSION']._serialized_start=247
  _globals['_SESSION']._serialized_end=374
  _globals['_CAPTION']._serialized_start=376
  _globals['_CAPTION']._serialized_end=457
# @@protoc_insertion_point(module_scope)
