"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Joint(google.protobuf.message.Message):
    """ข้อมูล Joint จาก BlazePose"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    X_FIELD_NUMBER: builtins.int
    Y_FIELD_NUMBER: builtins.int
    Z_FIELD_NUMBER: builtins.int
    VISIBILITY_FIELD_NUMBER: builtins.int
    id: builtins.int
    x: builtins.float
    y: builtins.float
    z: builtins.float
    visibility: builtins.float
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        x: builtins.float = ...,
        y: builtins.float = ...,
        z: builtins.float = ...,
        visibility: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "visibility", b"visibility", "x", b"x", "y", b"y", "z", b"z"]) -> None: ...

global___Joint = Joint

@typing.final
class Frame(google.protobuf.message.Message):
    """ข้อมูลในแต่ละเฟรม"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER_ID_FIELD_NUMBER: builtins.int
    SESSION_ID_FIELD_NUMBER: builtins.int
    FRAME_NO_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    JOINTS_FIELD_NUMBER: builtins.int
    FEATURES_FIELD_NUMBER: builtins.int
    LABELS_TH_FIELD_NUMBER: builtins.int
    user_id: builtins.str
    session_id: builtins.str
    frame_no: builtins.int
    timestamp: builtins.float
    """Unix timestamp"""
    @property
    def joints(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Joint]:
        """Raw joints data"""

    @property
    def features(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Engineered features vector"""

    @property
    def labels_th(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """Labels ภาษาไทย (ถ้ามี)"""

    def __init__(
        self,
        *,
        user_id: builtins.str = ...,
        session_id: builtins.str = ...,
        frame_no: builtins.int = ...,
        timestamp: builtins.float = ...,
        joints: collections.abc.Iterable[global___Joint] | None = ...,
        features: collections.abc.Iterable[builtins.float] | None = ...,
        labels_th: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["features", b"features", "frame_no", b"frame_no", "joints", b"joints", "labels_th", b"labels_th", "session_id", b"session_id", "timestamp", b"timestamp", "user_id", b"user_id"]) -> None: ...

global___Frame = Frame

@typing.final
class Session(google.protobuf.message.Message):
    """ข้อมูล Metadata ของแต่ละ Session"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    USER_ID_FIELD_NUMBER: builtins.int
    DEVICE_INFO_FIELD_NUMBER: builtins.int
    START_TS_FIELD_NUMBER: builtins.int
    END_TS_FIELD_NUMBER: builtins.int
    CALIBRATION_DATA_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    user_id: builtins.str
    device_info: builtins.str
    """e.g., "iPhone 11, Safari" """
    start_ts: builtins.float
    end_ts: builtins.float
    calibration_data: builtins.bytes
    """Protobuf ของ Frame ที่ใช้ calibrate"""
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        user_id: builtins.str = ...,
        device_info: builtins.str = ...,
        start_ts: builtins.float = ...,
        end_ts: builtins.float = ...,
        calibration_data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["calibration_data", b"calibration_data", "device_info", b"device_info", "end_ts", b"end_ts", "session_id", b"session_id", "start_ts", b"start_ts", "user_id", b"user_id"]) -> None: ...

global___Session = Session

@typing.final
class Caption(google.protobuf.message.Message):
    """ข้อมูล Caption จาก ASR"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    START_TIME_FIELD_NUMBER: builtins.int
    END_TIME_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    session_id: builtins.str
    start_time: builtins.float
    end_time: builtins.float
    text: builtins.str
    def __init__(
        self,
        *,
        session_id: builtins.str = ...,
        start_time: builtins.float = ...,
        end_time: builtins.float = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["end_time", b"end_time", "session_id", b"session_id", "start_time", b"start_time", "text", b"text"]) -> None: ...

global___Caption = Caption
