# configs/poseaug_config.yaml

# Dataset and data processing settings
dataset:
  joints: 33 # We are back to using raw 33 joints for PoseAug
  input_dim: 3 # 3D coordinates (x, y, z)
  window_size: 32
  stride: 8
  
# Augmentation settings
augmentation:
  poseaug:
    enabled: true
    # Bone Angle (BA) augmentation parameters
    ba_std_dev: 0.2
    # Bone Length (BL) augmentation parameters
    bl_std_dev: 0.15
    # Random Translation/Rotation (RT) augmentation parameters
    rt_yaw_deg: 20
    rt_pitch_deg: 10
    rt_roll_deg: 5
  occlusion:
    p_mask: 0.1

# Model architecture settings
model:
  encoder: tcn_gru
  tcn:
    blocks: [1, 2, 3]                  # List of TCN block counts to sweep
    channels: [256, 256, 256]          # Keep constant for now
    kernel: 3
    dilation_levels: [1, 2, 4, 8]      # List of dilation levels to sweep
  pooling:
    type: ['none', 'average', 'max']   # List of pooling types to sweep
    pool_size: 4
  gru:
    layers: [1, 2, 3]                  # List of GRU layers to sweep
    hidden: [64, 128, 256]             # List of GRU hidden units to sweep
    dropout: 0.2
  
# Heads for multi-task learning
heads:
  pos_regression:
    enabled: true
    hidden: 128
    output_dim: 99 # 33 joints * 3 dimensions
  angle_regression:
    enabled: true
    hidden: 128
    output_dim: 6  # 6 angles as a regression target
  classification:
    enabled: true
    hidden: 64    
    output_dim: 1

# Loss function settings
loss:
  w_pos: 1.0 # Weight for L_pos
  w_angle: 0.5 # Weight for L_angle
  w_bce: 0.2 # Weight for L_bce
# Database connection
database:
  host: "localhost"
  port: 5433
  dbname: "rehab_db"
  user: "nonny"
  password: "nonny"

# Training loop settings
training:
  epochs: 120
  batch_size: 32
  lr: 0.001
  weight_decay: 0.0001
  optimizer: AdamW
  mixed_precision: true
  early_stop_patience: 10
  exercise_name: "Jump squats"
  
# Logging settings
logging:
  log_dir: "results"
  log_file: "poseaug_sweep.csv"